version: "3.7"

services:
  app:
    build: ./
    networks:
      - default
      - localhost
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=8080
    volumes:
      - .:/var/www/html:Z

networks:
  localhost:
    external: true
